Models/EditHeadingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TransparencyAuditPublic.Models
{
    public class EditHeadingModel:HeadingModel
    {
        
        public string hdn_H3_CATEGORYDETAILS_ID { get; set; }
        public string hdn_H3_LINK { get; set; }
        public string hdn_H3_GUID { get; set; }

        //public string hdn_H3_ID { get; set; }
        
    }
}

Models/HeadingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TransparencyAuditPublic.Models
{
    public class HeadingModel
    {
        public string hdn_H3_ID { get; set; }
        public string H3_GUID { get; set; }
        public string H3_CATEGORYDETAILS_ID { get; set; }
        public string H3_LINK { get; set; }
        public string SUBJECT { get; set; }
        public string TEXT { get; set; }
        public string REMARKS { get; set; }
        public string H3_ID { get; set; }
        public string ISDELETE { get; set; }
        public List<UploadDetails> UploadDetailsList { get; set; }
        public string HEADING_FileUpload { get; set; }
        public string REMARKS_FileUpload { get; set; }

    }
    public class UploadDetails
    {
        public string FILEUPLOADDETAILS_ID { get; set; }
        public string HEADING { get; set; }
        public string REMARKS { get; set; }
        public string TITLE { get; set; }
        public string FILENAME { get; set; }
        public string FILESIZE { get; set; }  
        public string FILEPATH { get; set; }
        public string PUBLISHDATE { get; set; }
        public string H3_CATEGORYDETAILS_ID { get; set; }
        public string H3_GUID { get; set; }
        public bool SHOW_OR_NOT { get; set; }
        public string UPDATED_ON { get; set; }
        public string ISDELETE { get; set; }

    }
    public class HeadingIndexList
    {
        public List<H1_CATEGORYMASTER> H1_CATEGORYMASTER_List { get; set; }
        public List<H2_CATEGORYMASTER > H2_CATEGORYMASTER_List { get; set; }
        public List<H3_CATEGORYMASTER> H3_CATEGORYMASTER_List { get; set; }
    }
    public class H1_CATEGORYMASTER
    {
        public string H1_ID { get; set; }
        public string H1_LINK { get; set; }
        public string H1_NAME { get; set; }
        public string H1_ISDELETE { get; set; }
    }
    public class H2_CATEGORYMASTER
    {
        public string H2_ID { get; set; }
        public string H2_LINK { get; set; }
        public string H2_NAME { get; set; }
        public string H1_ID { get; set; }
        public string H1_LINK { get; set; }
        public string H2_ISDELETE { get; set; }
    }
    public class H3_CATEGORYMASTER
    {
        public string H3_ID { get; set; }
        public string H3_LINK { get; set; }
        public string H3_NAME { get; set; }
        public string H1_ID { get; set; }
        public string H2_ID { get; set; }
        public string H1_LINK { get; set; }
        public string H2_LINK { get; set; }
        public string H3_ISDELETE { get; set; }
    }
}

//public class AUDIT_ITEM
//{
//    public string PAGE_ID { get; set; }
//    public int SEQ1 { get; set; }
//    public int SEQ2 { get; set; }
//    public int SEQ3 { get; set; }
//    public string TITLE { get; set; }
//    public int IS_ACTIVE { get; set; }
//}

//@foreach(var item in ViewBag.auditlist)
//                                {
//    if (item.SEQ2 == 0)
//    {
//                                        < div class= "pl-0" >< b class= "pr-2" > @item.SEQ1 </ b >< b > @item.TITLE </ b ></ div >
//                                    }
//                                    else if (item.SEQ3 == 0)
//{
//                                        < div class= "pl-2" >< b class= "pr-2" > @item.SEQ1.@item.SEQ2 </ b >< b > @item.TITLE </ b ></ div >
//                                    }
//                                    else
//{
//                                        < div class= "pl-4" >< b class= "pr-2" > @item.SEQ1.@item.SEQ2.@item.SEQ3 </ b >< a href = "@Url.Action("Edit ","TransparencyAudit ", new {pageid = @item.PAGE_ID})" > @item.TITLE </ a ></ div >
//                                    }
//                                }

Models/ViewHeadingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TransparencyAuditPublic.Models
{
    public class ViewHeadingModel: EditHeadingModel
    {

    }
}

Controllers/TransparencyAuditPublicController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using TransparencyAuditPublic.Models;

namespace TransparencyAuditPublic.Controllers
{
    public class TransparencyAuditPublicController : Controller
    {
        private ITransparencyAuditPublic interfaceobj;
        public TransparencyAuditPublicController()
                : this(new ITransparencyAuditPublicServices())
        {
        }

        public TransparencyAuditPublicController(ITransparencyAuditPublic interobj)
        {
            interfaceobj = interobj;

        }
        // GET: TransparencyAudit
        [HttpGet]
        public ActionResult HeadingIndexListPublic()
        {
            HeadingIndexList headingIndexList = new HeadingIndexList();
            headingIndexList.H1_CATEGORYMASTER_List = interfaceobj.GetH1CATEGORYMASTERList();
            headingIndexList.H2_CATEGORYMASTER_List = interfaceobj.GetH2CATEGORYMASTERList();
            headingIndexList.H3_CATEGORYMASTER_List = interfaceobj.GetH3CATEGORYMASTERList();
            return View(headingIndexList);
        }
        [HttpGet]
        public ActionResult ViewHeadingPublic(string H3_LINK,string H3_ID,string H3_NAME)
        {
            ViewHeadingModel viewHeadingModel = new ViewHeadingModel();
            var getH3_CATEGORYDETAILS = interfaceobj.GetH3_CATEGORYDETAILS(H3_LINK);
            var getFILEUPLOADDETAILS=new List<UploadDetails>();
            if (getH3_CATEGORYDETAILS.H3_GUID!=null)
            {
                getFILEUPLOADDETAILS = interfaceobj.GetFILEUPLOADDETAILS_SHOW(getH3_CATEGORYDETAILS.H3_GUID);
            } 
            if (getH3_CATEGORYDETAILS.H3_LINK != null && getH3_CATEGORYDETAILS.H3_GUID!=null && getFILEUPLOADDETAILS.Count != 0)
            {
                var ViewHeading = new ViewHeadingModel
                {
                    hdn_H3_CATEGORYDETAILS_ID = getH3_CATEGORYDETAILS.H3_CATEGORYDETAILS_ID,
                    hdn_H3_GUID = getH3_CATEGORYDETAILS.H3_GUID,
                    hdn_H3_LINK = getH3_CATEGORYDETAILS.H3_LINK,
                    hdn_H3_ID = getH3_CATEGORYDETAILS.H3_ID,
                    H3_CATEGORYDETAILS_ID = getH3_CATEGORYDETAILS.H3_CATEGORYDETAILS_ID,
                    H3_GUID = getH3_CATEGORYDETAILS.H3_GUID,
                    H3_LINK = getH3_CATEGORYDETAILS.H3_LINK,
                    TEXT = getH3_CATEGORYDETAILS.TEXT,
                    REMARKS = getH3_CATEGORYDETAILS.REMARKS,
                    SUBJECT = getH3_CATEGORYDETAILS.SUBJECT,
                    HEADING_FileUpload = getH3_CATEGORYDETAILS.HEADING_FileUpload,
                    REMARKS_FileUpload = getH3_CATEGORYDETAILS.REMARKS_FileUpload,
                    UploadDetailsList = getFILEUPLOADDETAILS

                };
                viewHeadingModel = ViewHeading;
            }
            else
            {
                var ViewHeading = new ViewHeadingModel
                {
                    H3_LINK = H3_LINK,
                    SUBJECT = H3_NAME
                };
                viewHeadingModel = ViewHeading;
            }
            return View(viewHeadingModel);
        }

        public ActionResult DownloadFile(string FILENAME)
        {
            byte[] filedata = null;
            string contentType = "";
            try
            {
                //string uploadsFolder = Server.MapPath("~/UploadFiles/");
                string uploadsFolder = OracleDBHelper.UploadFilePath;
                string path = Path.Combine(uploadsFolder, FILENAME);
                filedata = System.IO.File.ReadAllBytes(HttpUtility.HtmlEncode(path));
                contentType = "application/octet-stream";
                var cd = new System.Net.Mime.ContentDisposition
                {
                    FileName = FILENAME,
                    Inline = true,
                };
                Response.Headers.Add("Content-Disposition", cd.ToString());
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
            return File(filedata, contentType);
        }
        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DGH</title>
    @*@Styles.Render("~/Content/css")*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    @*@Scripts.Render("~/bundles/modernizr")*@
    <style>

    </style>
</head>
<body>
    @*<div id="topheader">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="@Url.Action("HeadingIndexList","TransparencyAudit")">Transparency Audit</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="@Url.Action("HeadingIndexList","TransparencyAudit")">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("About","Home")">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Contact","Home")">Contact</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </div>*@

    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - DGH INDIA</p>
        </footer>*@
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="~/Content/jquery.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/TransparencyAuditPublic/HeadingIndexListPublic.cshtml
@model TransparencyAuditPublic.Models.HeadingIndexList
@{
    ViewBag.Title = "HeadingIndexListPublic";
    //Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Heading Index List</title>
    <script src="~/Themes/ckeditor/ckeditor.js"></script>
    <style>
        .card-body {
            /*background-color: rgba(0, 0, 0, 0.03);*/
            background-color: white;
        }
        .card-header {
            /*background-color: rgba(0, 0, 0, 0.03);*/
            background-color: white;
        }
    </style>
</head>
<body>
    <div class="container px-5 py-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card mb-5 border border-0">
                    <h4 class="card-header text-left border-bottom-0">Transparency Audit</h4>
                    <div class="card-body">
                        @foreach (var h1 in Model.H1_CATEGORYMASTER_List)
                        {
                            List<TransparencyAuditPublic.Models.H2_CATEGORYMASTER> h2List = Model.H2_CATEGORYMASTER_List.Where(x => x.H1_LINK == h1.H1_LINK).ToList();
                            <ul style="text-align: left; list-style: none">
                                <li style="font-size:17px;font-weight:500;">
                                    <label>@h1.H1_LINK &nbsp;&nbsp; @h1.H1_NAME</label>
                                    <ul style="text-align: left; list-style: none">
                                        @foreach (var h2 in h2List)
                                        {
                                            List<TransparencyAuditPublic.Models.H3_CATEGORYMASTER> h3List = Model.H3_CATEGORYMASTER_List.Where(x => x.H1_LINK == h2.H1_LINK && x.H2_LINK == h2.H2_LINK).ToList();
                                            <li style="font-size:17px;">
                                                <label>@h2.H2_LINK &nbsp;&nbsp; @h2.H2_NAME</label>
                                                <ul style="text-align: left; list-style: none">
                                                    @foreach (var h3 in h3List)
                                                    {
                                                        <li style="font-size: 15px;">
                                                            @h3.H3_LINK &nbsp;&nbsp;<a style="color: black;font-weight: 400;" href="@Url.Action("ViewHeadingPublic", "TransparencyAuditPublic", new RouteValueDictionary(new { H3_LINK = h3.H3_LINK,H3_ID=h3.H3_ID,H3_NAME= h3.H3_NAME}))">@h3.H3_NAME</a>
                                                        </li>
                                                    }
                                                </ul>
                                            </li>
                                        }
                                    </ul>
                                </li>

                            </ul>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/TransparencyAuditPublic/ViewHeadingPublic.cshtml
@model TransparencyAuditPublic.Models.ViewHeadingModel

@{
    ViewBag.Title = "ViewHeadingPublic";
    //Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Transparency Audit</title>
    <script src="~/Themes/ckeditor/ckeditor.js"></script>
    <style>
        textarea {
            resize: none;
        }
        .card-body {
            /*background-color: rgba(0, 0, 0, 0.03);*/
            background-color: white;
        }
        .card-header {
            /*background-color: rgba(0, 0, 0, 0.03);*/
            background-color: #053671;
            color: white;
        }
        table thead {
            background-color: #053671;
            color:white;
        }
    </style>
</head>
<body>
    <div class="container px-5 py-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card mb-5 border border-0">
                    @if ((Model.H3_LINK != null && Model.H3_LINK != "") && (Model.SUBJECT != null && Model.SUBJECT != ""))
                    {
                        <h4 class="card-header text-left rounded-0">@Html.DisplayFor(m => m.H3_LINK, new { @class = "form-control", @readonly = true, @id = "h3_LINK" })&nbsp;&nbsp;@Html.DisplayFor(m => m.SUBJECT, new { @class = "form-control", @readonly = true, @id = "subject" })</h4>
                    }
                    <div class="card-body">
                        <form class="row g-3">
                            @Html.HiddenFor(m => m.hdn_H3_ID, new { @id = "hdn_H3_ID" })
                            @Html.HiddenFor(m => m.hdn_H3_LINK, new { @id = "hdn_H3_LINK" })
                            @Html.HiddenFor(m => m.hdn_H3_GUID, new { @id = "hdn_H3_GUID" })
                            @Html.HiddenFor(m => m.hdn_H3_CATEGORYDETAILS_ID, new { @id = "hdn_H3_CATEGORYDETAILS_ID" })
                            @if (Model.TEXT != null && Model.TEXT != "")
                            {
                                @*<div class="col-12">
                                    @Html.TextAreaFor(m => m.TEXT, new { @class = "form-control bg-light", @readonly = true, @rows = "2", @id = "text" })
                                </div>*@
                                <div class="col-12">
                                    <table class="table table-bordered table-responsive">
                                        <tr>
                                            <td>@Html.Raw(Model.TEXT)</td>
                                        </tr>
                                    </table> 
                                </div>
                            }
                            @if (Model.REMARKS != null && Model.REMARKS != "")
                            {
                        <div class="col-12">
                            <label for="remarks" class="form-label" style="font-weight:700">Remarks</label>
                            @*@Html.TextAreaFor(m => m.REMARKS, new { @class = "form-control bg-light", @readonly = true, @rows = "3", @id = "remarks" })*@
                            <table class="table table-bordered table-responsive">
                                <tr>
                                    <td>@Html.Raw(Model.REMARKS)</td>
                                </tr>
                            </table>
                        </div>
                            }
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card border border-0">
                    @if (Model.HEADING_FileUpload != null && Model.HEADING_FileUpload != "")
            {
                    <h4 class="card-header text-left rounded-0">@Html.DisplayFor(m => m.HEADING_FileUpload, new { @class = "heading form-control", @id = "heading" })</h4>
            }
                        
                    <div class="card-body">
                        <form class="row g-3">
                           
                            @if (Model.REMARKS_FileUpload != null && Model.REMARKS_FileUpload != "")
                            {
                                <div class="col-12">
                                    <label for="remarks" class="form-label" style="font-weight:700">Remarks</label>
                                    @Html.TextAreaFor(m => m.REMARKS_FileUpload, new { @class = "remarksForHeading form-control", @readonly = true, @rows = "3", @id = "remarksForHeading" })
                                </div>
                            }
                            
                            @if ((Model.H3_GUID != null) && (Model.UploadDetailsList != null))
                            {
                                <table class="table table-bordered table-responsive" id="RegularEmp">
                                    <thead>
                                        <tr>
                                            <th>Sr. No.</th>
                                            <th>Title</th>
                                            <th>File</th>
                                            <th>Publish Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{ int counter = 1;}
                                        @foreach (var file in Model.UploadDetailsList)
                                        {
                                            <tr>
                                                <td>@counter</td>
                                                <td>@Html.DisplayFor(m => file.TITLE, new { @class = "title form-control", @id = "titleU" })</td>
                                                <td>@Html.ActionLink("DownloadFile", "DownloadFile", "TransparencyAuditPublic", new { fileName = file.FILENAME }, new { target = "_blank" }) </td>
                                                <td>@Html.DisplayFor(m => file.PUBLISHDATE, new { @class = "publishdate form-control", @id = "publishdateU", @type = "date" })</td>
                                            </tr>
                                            counter = counter + 1;
                                        }
                                    </tbody>
                                </table>
                            }
                        </form>
                    </div>
                </div>
            </div>
            @*<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row py-3">
                    <div class="col-sm-5"></div>
                    <div class="col-sm-7">
                        <a href='@Url.Action("HeadingIndexListPublic", "TransparencyAuditPublic")' class="btn btn-primary">BACK</a>
                    </div>
                </div>
            </div>*@
        </div>
    </div>
    <script>
    </script>
</body>
</html>